// <auto-generated />
using Anker.WeiXin.MP.CoreDynamicShow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Anker.WeiXin.MP.CoreDynamicShow.Migrations
{
    [DbContext(typeof(DynamicShowContext))]
    [Migration("20180507065636_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.CommonService.MyWebsite.HandlersServer.Models.ConfigModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Titlt");

                    b.HasKey("ID");

                    b.ToTable("ConfigModel");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.CommonService.MyWebsite.HandlersServer.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Email");

                    b.Property<string>("IP");

                    b.Property<string>("Image");

                    b.Property<string>("NickName");

                    b.Property<int>("State");

                    b.Property<DateTime>("Time");

                    b.Property<int>("UserID");

                    b.Property<string>("Website");

                    b.Property<string>("address");

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("province");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.CommonService.MyWebsite.HandlersServer.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Email");

                    b.Property<string>("IP");

                    b.Property<string>("Image");

                    b.Property<string>("NickName");

                    b.Property<int>("State");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Website");

                    b.Property<string>("address");

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("province");

                    b.Property<int>("ticket");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinArticle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int?>("UserInfoID");

                    b.HasKey("ID");

                    b.HasIndex("UserInfoID");

                    b.ToTable("WeiXinArticle");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinArticleInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AIDID");

                    b.Property<int>("Amount");

                    b.Property<DateTime>("ClockEnd");

                    b.Property<DateTime>("ClockStart");

                    b.Property<int>("OpentNumber");

                    b.Property<int>("SpendingDate");

                    b.Property<int?>("UIDID");

                    b.HasKey("ID");

                    b.HasIndex("AIDID");

                    b.HasIndex("UIDID");

                    b.ToTable("WeiXinArticleInfo");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinUserInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("headimgurl");

                    b.Property<string>("nickname");

                    b.Property<string>("openid");

                    b.Property<string>("province");

                    b.Property<int>("sex");

                    b.Property<string>("unionid");

                    b.HasKey("ID");

                    b.ToTable("WeiXinUserInfo");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.CommonService.MyWebsite.HandlersServer.Models.Message", b =>
                {
                    b.HasOne("Anker.WeiXin.MP.CoreDynamicShow.CommonService.MyWebsite.HandlersServer.Models.User")
                        .WithMany("Meaages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinArticle", b =>
                {
                    b.HasOne("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinUserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoID");
                });

            modelBuilder.Entity("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinArticleInfo", b =>
                {
                    b.HasOne("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinArticle", "AID")
                        .WithMany()
                        .HasForeignKey("AIDID");

                    b.HasOne("Anker.WeiXin.MP.CoreDynamicShow.Models.WeiXinUserInfo", "UID")
                        .WithMany()
                        .HasForeignKey("UIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
